// Generated from qualitative text PDFs so text samples render as DOM text, not images.
// Regenerate with pdftotext if the source text PDFs change.
export const muniTextAssets = {
  "figures/muni/qualitative/qualitative_ita/A_to_T/012_codi_text.pdf": "A baby is crying and mother is born.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/012_flowbind_text.pdf": "A infant crying and a woman speaking.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/012_omniflow_text.pdf": "A woman and baby talking.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/012_ours_hell_200_text.pdf": "A woman is talking to a baby while he cries.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/024_codi_text.pdf": "People typing.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/024_flowbind_text.pdf": "A woman speaks and then a person talks keyboard.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/024_omniflow_text.pdf": "A man speaks and types on a keyboard.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/024_ours_hell_200_text.pdf": "Two people talking and typing on a computer keyboard.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/046_codi_text.pdf": "One dog coming to turn for a speeding car are speeding away.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/046_flowbind_text.pdf": "A boat motor is cruising then slows somewhat loudly.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/046_omniflow_text.pdf": "Wind blows and an engine hums.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/046_ours_hell_200_text.pdf": "A motorboat engine running and revving.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/058_codi_text.pdf": "Cat starts a cat < baby.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/058_flowbind_text.pdf": "Loud meowing of cat, then meowing.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/058_omniflow_text.pdf": "A cat meows and whines.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/058_ours_hell_200_text.pdf": "A cat is howling and the wind is blowing.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/073_codi_text.pdf": "The man laughs to congratulate the man who says that the election is about to yell.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/073_flowbind_text.pdf": "A man speaks with people talking then he applauds.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/073_omniflow_text.pdf": "Man speaking into a microphone.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/073_ours_hell_200_text.pdf": "A man is speaking to an audience while others clap.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/118_codi_text.pdf": "Jump happening in a fire over a falling lake and blue rainbow.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/118_flowbind_text.pdf": "Multiple popping and eruption.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/118_omniflow_text.pdf": "Rain falls and a pop occurs.",
  "figures/muni/qualitative/qualitative_ita/A_to_T/118_ours_hell_200_text.pdf": "Fireworks burst in the sky and then a burst.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/014_codi_text.pdf": "Mike mitt kicks his playoff pitch during the final baseball game of the year.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/014_flowbind_text.pdf": "A boy in a white baseball uniform, shirt and visor is holding a baseball bat.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/014_omniflow_text.pdf": "A young boy throwing a baseball with a baseball bat.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/014_ours_hell_200_text.pdf": "A young boy in a baseball uniform is excited after catching a ball.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/039_codi_text.pdf": "Dog and a bag lunch on coffee.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/039_flowbind_text.pdf": "A helmet with books on it sitting on a table with a dog and coffee.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/039_omniflow_text.pdf": "A paper bag with a sandwich and a knife sitting on a wooden table.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/039_ours_hell_200_text.pdf": "A cup and donut on a table with books.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/065_codi_text.pdf": "Apple with peanuts.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/065_flowbind_text.pdf": "A pan with some banana flour on it.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/065_omniflow_text.pdf": "A pan filled with fried rice and shrimp.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/065_ours_hell_200_text.pdf": "A skillet with bananas and syrup being cooked.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/069_codi_text.pdf": "On a hill with horses and bicyclists on a truck four people don't stop.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/069_flowbind_text.pdf": "A man riding a bucking cow is driving down a road past a herd of cows.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/069_omniflow_text.pdf": "A herd of cows walking down a road in a forest, with a truck parked nearby.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/069_ours_hell_200_text.pdf": "A man in a tractor with cows on the road.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/077_codi_text.pdf": "All women finals at the 2012 olympic skiing, multiple women in the 100 olympic.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/077_flowbind_text.pdf": "A man skis down a snowy hill as he is sliding off of a race track.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/077_omniflow_text.pdf": "A person is skiing through a snowy landscape with footprints.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/077_ours_hell_200_text.pdf": "A skier in purple is sliding down the slope.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/080_codi_text.pdf": "Two guys making some pizza on the pizza.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/080_flowbind_text.pdf": "A little girl is cooking pizza with a plate, while a toddler is making it.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/080_omniflow_text.pdf": "Two children are sitting at a table with dishes.",
  "figures/muni/qualitative/qualitative_ita/I_to_T/080_ours_hell_200_text.pdf": "Two little girls are making pizzas in the kitchen.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/013_codi_text.pdf": "A man stops for a train about to go on a car being driven by a man.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/013_flowbind_text.pdf": "The vehicle motor is driving down the road.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/013_omniflow_text.pdf": "A man sits in a truck, working on an engine.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/013_ours_hell_200_text.pdf": "A man walking next to a small car.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/0_codi_text.pdf": "A man is speaking to a person in the city talking while walking for the man.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/0_flowbind_text.pdf": "A man sitting at a park bench while music is playing.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/0_omniflow_text.pdf": "A man talking with a crowd talking in the background.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/0_ours_hell_200_text.pdf": "A man playing an acoustic guitar and another person sitting on the bench.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/1_codi_text.pdf": "A man is jaying after a dog says to his dog greeting. as he walks on the dog.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/1_flowbind_text.pdf": "A man speaking with someone.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/1_omniflow_text.pdf": "A man talking in a movie, with a blurry background.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/1_ours_hell_200_text.pdf": "A man is talking to some people and there is a dog.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/203_codi_text.pdf": "Red traffic car for a road red.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/203_flowbind_text.pdf": "A police siren is signaling while sirens are.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/203_omniflow_text.pdf": "A darkened city street with a siren blaring in the distance,.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/203_ours_hell_200_text.pdf": "A police car is going by with sirens.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/256_codi_text.pdf": "Airplane.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/256_flowbind_text.pdf": "A helicopter flying over with muffled helicopter.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/256_omniflow_text.pdf": "A helicopter hovering in the distance, with.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/256_ours_hell_200_text.pdf": "A helicopter is flying through the air.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/366_codi_text.pdf": "Man driving in a blue car race to turn mid-way on his car engine, is speeding.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/366_flowbind_text.pdf": "A man motor is on a boat in the water boating.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/366_omniflow_text.pdf": "A man is working on a boat in the water.",
  "figures/muni/qualitative/qualitative_ita/IandA_to_T/366_ours_hell_200_text.pdf": "A man in sunglasses is driving on the water.",
  "figures/muni/qualitative/qualitative_ita/T_to_I/0_src_text.pdf": "Modern bedroom with large desk in front of window.",
  "figures/muni/qualitative/qualitative_ita/T_to_I/1_src_text.pdf": "A wooden table surrounded by chairs next to a TV.",
  "figures/muni/qualitative/qualitative_ita/T_to_I/2_src_text.pdf": "A dog is patiently waiting in the back of a truck.",
  "figures/muni/qualitative/qualitative_ita/T_to_I/3_src_text.pdf": "A bathroom sink with a bottle of hand soap.",
  "figures/muni/qualitative/qualitative_ita/T_to_I/4_src_text.pdf": "A red park bench sitting in the middle of a flooded area.",
  "figures/muni/qualitative/qualitative_ita/T_to_I/5_src_text.pdf": "A vase with flowers next to a clock.",
  "figures/muni/qualitative/qualitative_ita/TandA_to_I/0_src_text.pdf": "A vehicle is running on the mountain.",
  "figures/muni/qualitative/qualitative_ita/TandA_to_I/1_src_text.pdf": "A woman is speaking in the hospital.",
  "figures/muni/qualitative/qualitative_ita/TandA_to_I/2_src_text.pdf": "There is a man in front of the building.",
  "figures/muni/qualitative/qualitative_ita/TandA_to_I/3_src_text.pdf": "A man is standing outside.",
  "figures/muni/qualitative/qualitative_ita/TandA_to_I/4_src_text.pdf": "It's a sunny day.",
  "figures/muni/qualitative/qualitative_ita/TandA_to_I/5_src_text.pdf": "A man is on the outside.",
  "figures/muni/qualitative/qualitative_ita/uncond/generalists/483_omniflow_caption_text.pdf": "Drums and horses playing.",
  "figures/muni/qualitative/qualitative_ita/uncond/generalists/483_ours_hell_200_caption_text.pdf": "A car is driving by and it speeds by.",
  "figures/muni/qualitative/qualitative_ita/uncond/generalists/484_omniflow_caption_text.pdf": "The destroyed children are in the heart of a skull.",
  "figures/muni/qualitative/qualitative_ita/uncond/generalists/484_ours_hell_200_caption_text.pdf": "Two people standing on top of a mountain.",
  "figures/muni/qualitative/qualitative_ita/uncond/mvaes/241_moe_200_caption_text.pdf": "A man in a hat and coat walking down the street.",
  "figures/muni/qualitative/qualitative_ita/uncond/mvaes/241_mopoe_200_caption_text.pdf": "A person on top of a mountain with skis.",
  "figures/muni/qualitative/qualitative_ita/uncond/mvaes/241_ours_hell_200_caption_text.pdf": "A bird perched on top of a tree branch.",
  "figures/muni/qualitative/qualitative_ita/uncond/mvaes/451_moe_200_caption_text.pdf": "A man preparing food in the kitchen of his home.",
  "figures/muni/qualitative/qualitative_ita/uncond/mvaes/451_mopoe_200_caption_text.pdf": "A man singing and playing the guitar.",
  "figures/muni/qualitative/qualitative_ita/uncond/mvaes/451_ours_hell_200_caption_text.pdf": "A table with chairs and flowers on it.",
  "figures/muni/qualitative/qualitative_ita/uncond_ours/ours_hell_200_078_caption_text.pdf": "A group of people with bicycles in the grass.",
  "figures/muni/qualitative/qualitative_ita/uncond_ours/ours_hell_200_145_caption_text.pdf": "A man with an acoustic guitar and shirt.",
  "figures/muni/qualitative/qualitative_ita/uncond_ours/ours_poe_200_050_caption_text.pdf": "The room has blue curtains and red furniture.",
  "figures/muni/qualitative/qualitative_ita/uncond_ours/ours_poe_200_255_caption_text.pdf": "The beach is empty and clear with palm trees.",
} as const satisfies Record<string, string>;
